version: '3.4'

services:
  belote-backend:
    image: belote-backend:latest
    build:
      context: .
      dockerfile: Startup/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=belote-database;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    ports:
      - "5222:80"
    depends_on:
      - belote-database
    networks:
      - belote-network

  belote-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - belote-data:/var/lib/postgresql/data
    ports:
      - "5333:5432"
    networks:
      - belote-network

volumes:
  belote-data:

networks:
  belote-network:
    driver: bridge