version: '3.4'

services:
  belote-startup:
    image: belote-startup
    build:
      context: ../
      dockerfile: src/backend/Startup/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=belote-db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    ports:
      - "5200:80"
    depends_on:
      - belote-db
    networks:
      - belote-network

  belote-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - belote-data:/var/lib/postgresql/data
    networks:
      - belote-network

volumes:
  belote-data:

networks:
  belote-network:
    driver: bridge
