version: '3.4'

services:
  belote-backend:
    image: belote-backend
    build:
      context: ../src/backend
      dockerfile: Startup/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=belote-database;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    ports:
      - "5200:80"
    depends_on:
      - belote-database
    networks:
      - belote-network
    volumes:
      - config-data:/app/config 

  belote-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - belote-data:/var/lib/postgresql/data
    networks:
      - belote-network

  belote-reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/nginx/certs
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - belote-backend
    networks:
      - belote-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certs:/etc/nginx/certs
    entrypoint: "sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  belote-data:
  config-data: # New volume for configuration/status files
  certbot-etc: # New volume for certbot's configuration files
  certbot-var: # New volume for certbot's data
  certs: # New volume to store the certificates

networks:
  belote-network:
    driver: bridge
