version: '3.4'

services:
  belote-backend:
    image: belote-backend
    build:
      context: ../src/backend
      dockerfile: Startup/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=belote-database;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    depends_on:
      - belote-database
    networks:
      - belote-network

  belote-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - belote-data:/var/lib/postgresql/data
    networks:
      - belote-network

  belote-reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - belote-backend
    networks:
      - belote-network

volumes:
  belote-data:

networks:
  belote-network:
    driver: bridge
