name: Deploy to Linode VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      LINODE_HOST: ${{ secrets.LINODE_HOST }}
      LINODE_USERNAME: ${{ secrets.LINODE_USERNAME }}
      LINODE_SSH_KEY: ${{ secrets.LINODE_SSH_KEY }}
      DEPLOY_PATH: ${{ env.DEPLOYMENT_PATH }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Linode
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.LINODE_HOST }}
          username: ${{ env.LINODE_USERNAME }}
          key: ${{ env.LINODE_SSH_KEY }}
          source: "."
          target: ${{ env.DEPLOY_PATH }}

      - name: Build and Restart services on Linode using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.LINODE_HOST }}
          username: ${{ env.LINODE_USERNAME }}
          key: ${{ env.LINODE_SSH_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}/deploy
            export DB_NAME="${{ env.DB_NAME }}"
            export DB_USER="${{ env.DB_USER }}"
            export DB_PASSWORD="${{ env.DB_PASSWORD }}"
            docker-compose -f docker-compose.prod.yml build
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d
